# Generated by Django 3.2.5 on 2022-07-19 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id_data', models.AutoField(primary_key=True, serialize=False)),
                ('in_date', models.DateField()),
                ('name_customer', models.CharField(max_length=200)),
                ('jobs', models.CharField(max_length=200)),
                ('out_date', models.DateField()),
                ('upload', models.FileField(upload_to='report')),
            ],
        ),
    ]
