# Generated by Django 3.2.5 on 2022-07-19 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200)),
                ('id_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.data')),
            ],
        ),
    ]
