# Generated by Django 3.2.5 on 2022-07-27 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='upload',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
