# Generated by Django 3.2.5 on 2022-07-29 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_data_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='upload',
            field=models.URLField(blank=True),
        ),
    ]
