# Generated by Django 3.2.5 on 2022-08-02 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_data_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_jobs', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='data',
            name='jobs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.jobs'),
        ),
    ]
